// List of known disposable/temporary email domains
// This is a curated list of the most common disposable email providers

export const DISPOSABLE_EMAIL_DOMAINS = [
  // Temporary email services
  '10minutemail.com',
  '10minutemail.net',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.biz',
  'spam4.me',
  'grr.la',
  'guerrillamailblock.com',
  'sharklasers.com',
  'pokemail.net',
  'mailinator.com',
  'mailinator2.com',
  'sogetthis.com',
  'mailinater.com',
  'mailinator.net',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courriel.fr.nf',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'tempmail.com',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.ru',
  'tempmail.net',
  'tempr.email',
  'throwaway.email',
  'trashmail.com',
  'trash-mail.com',
  'trash-mail.de',
  'trashemail.de',
  'thankyou2010.com',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spambox.us',
  'spambox.info',
  'spamex.com',
  'spamfree24.org',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.com',
  'spamgoes.in',
  'spamhole.com',
  'spamify.com',
  'spamkill.info',
  'spammotel.com',
  'spamobox.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamtrap.co',
  'getnada.com',
  'nada.email',
  'getairmail.com',
  'dropmail.me',
  'fakeinbox.com',
  'fakemailgenerator.com',
  'fakermail.com',
  'fakemail.fr',
  'fake-mail.ga',
  'fake-mail.ml',
  'fake-mail.cf',
  'fake-mail.tk',
  'emailondeck.com',
  'emailsensei.com',
  'emailtemporanea.com',
  'emailtemporanea.net',
  'emailtemporario.com.br',
  'dispostable.com',
  'disposeamail.com',
  'disposemail.com',
  'discard.email',
  'discard.cf',
  'discard.ga',
  'discard.gq',
  'discard.ml',
  'discard.tk',
  'burnermail.io',
  'harakirimail.com',
  'mytemp.email',
  'mytemp.email',
  'mytrashmail.com',
  'mohmal.com',
  'mintemail.com',
  'maildrop.cc',
  'mailnesia.com',
  'mailnator.com',
  'mailcatch.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailinator2.net',
  'mailinator2.org',
  'tmailinator.com',
  'zmail.com',
  'zemail.com',
];

/**
 * Check if email domain is in disposable list
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.toLowerCase().split('@')[1];
  if (!domain) return false;
  
  return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}
